# Mise is kinda dumb since install does not provide a way to find all tools that tasks depends on
# For certain CI tasks we want the mise cache to work properly

[tools]
# "aqua:gohugoio/hugo" = "0.147.9"
	hugo = "{{env.HUGO_VERSION}}"
	"cargo:emmylua_doc_cli" = "{{env.EMMYLUA_DOC_CLI_VERSION}}"
	"aqua:jqlang/jq" = "{{env.JQ_VERSION}}"
	"aqua:ip7z/7zip" = "{{env.7Z_VERSION}}"
	"npm:lua-doc-extractor" = "{{env.LUA_DOC_EXTRACTOR_VERSION}}"
	"ruby" = "{{env.RUBY_VERSION}}"
